# Generated by Django 3.2.6 on 2021-08-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assureur',
        ),
        migrations.RemoveField(
            model_name='baremedecredit',
            name='code_produit',
        ),
        migrations.RemoveField(
            model_name='baremedecredit',
            name='produitassurancee',
        ),
        migrations.RemoveField(
            model_name='baremedevoyage',
            name='code_produit',
        ),
        migrations.RemoveField(
            model_name='baremedevoyage',
            name='produitassurance',
        ),
        migrations.DeleteModel(
            name='Beneficiaire',
        ),
        migrations.DeleteModel(
            name='Clientpassager',
        ),
        migrations.RemoveField(
            model_name='comptebancaire',
            name='num_fiche_client',
        ),
        migrations.RemoveField(
            model_name='souscriptiondecredit',
            name='Num_dossierCredit',
        ),
        migrations.RemoveField(
            model_name='souscriptiondecredit',
            name='code_produit',
        ),
        migrations.RemoveField(
            model_name='souscriptiondevoyage',
            name='type_couverture',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='UG_actuel_id',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='code_groupe',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Baremedecredit',
        ),
        migrations.DeleteModel(
            name='Baremedevoyage',
        ),
        migrations.DeleteModel(
            name='ClientUIB',
        ),
        migrations.DeleteModel(
            name='Comptebancaire',
        ),
        migrations.DeleteModel(
            name='Credit',
        ),
        migrations.DeleteModel(
            name='Groupe',
        ),
        migrations.DeleteModel(
            name='Produitassurance',
        ),
        migrations.DeleteModel(
            name='Souscriptiondecredit',
        ),
        migrations.DeleteModel(
            name='Souscriptiondevoyage',
        ),
        migrations.DeleteModel(
            name='Unitedegestion',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
