# Generated by Django 3.2.6 on 2021-08-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0002_alter_produitassurance_code_assureur'),
        ('assurance', '0002_auto_20210817_0000'),
    ]

    operations = [
    ]
