# Generated by Django 3.1.7 on 2021-08-20 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0003_merge_20210820_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baremedevoyage',
            name='code_produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produitassurance', to='assurance.produitassurance'),
        ),
    ]
