# Generated by Django 3.1.7 on 2021-08-21 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0004_auto_20210820_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscriptiondevoyage',
            name='id_client',
        ),
        migrations.AddField(
            model_name='souscriptiondevoyage',
            name='Num_cin_passager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.clientpassager'),
        ),
        migrations.AddField(
            model_name='souscriptiondevoyage',
            name='Num_fiche_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.clientuib'),
        ),
    ]
