# Generated by Django 3.1.7 on 2021-08-21 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0005_auto_20210821_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscriptiondevoyage',
            name='Num_cin_passager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.clientpassager'),
        ),
        migrations.AlterField(
            model_name='souscriptiondevoyage',
            name='Num_fiche_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.clientuib'),
        ),
    ]
