# Generated by Django 3.1.7 on 2021-09-01 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0009_auto_20210830_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscriptiondevoyage',
            name='code_produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.produitassurance'),
        ),
        migrations.AlterField(
            model_name='baremedevoyage',
            name='type_couverture',
            field=models.CharField(choices=[('I', 'Individuel'), ('F', 'Familiale')], max_length=40),
        ),
    ]
