# Generated by Django 3.2.6 on 2021-09-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0010_auto_20210901_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscriptiondecredit',
            name='beneficiaires',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='souscriptiondevoyage',
            name='beneficiaires',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
