# Generated by Django 3.1.7 on 2021-09-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0011_auto_20210908_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baremedecredit',
            old_name='duree_max',
            new_name='date_debut',
        ),
        migrations.RemoveField(
            model_name='baremedecredit',
            name='duree_min',
        ),
        migrations.RemoveField(
            model_name='souscriptiondecredit',
            name='beneficiaires',
        ),
        migrations.RemoveField(
            model_name='souscriptiondevoyage',
            name='beneficiaires',
        ),
        migrations.AddField(
            model_name='baremedecredit',
            name='duree',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
