# Generated by Django 3.1.7 on 2021-09-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0012_auto_20210909_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscriptiondevoyage',
            name='Num_cin_passager',
        ),
        migrations.RemoveField(
            model_name='souscriptiondevoyage',
            name='type_client',
        ),
    ]
