# Generated by Django 3.1.7 on 2021-09-09 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0013_auto_20210909_2245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientpassager',
        ),
        migrations.RemoveField(
            model_name='beneficiaire',
            name='type_document',
        ),
        migrations.RemoveField(
            model_name='produitassurance',
            name='Periodicite_renversement',
        ),
        migrations.AlterField(
            model_name='souscriptiondevoyage',
            name='code_assureur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assurance.assureur'),
        ),
    ]
