# Generated by Django 3.1.7 on 2021-09-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0014_auto_20210909_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baremedevoyage',
            name='etat_bareme',
            field=models.CharField(choices=[('Valide', 'Valide'), ('En attente', 'En attente')], max_length=40),
        ),
        migrations.AlterField(
            model_name='souscriptiondecredit',
            name='etat_sous_credit',
            field=models.CharField(choices=[('Valide', 'Valide'), ('En attente', 'En attente')], max_length=40),
        ),
        migrations.AlterField(
            model_name='souscriptiondevoyage',
            name='duree',
            field=models.CharField(max_length=40),
        ),
    ]
