# Generated by Django 3.1.7 on 2021-09-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0015_auto_20210909_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscriptiondevoyage',
            name='beneficiaires',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
