# Generated by Django 3.1.7 on 2021-09-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0018_alter_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaire',
            name='num_souscription',
        ),
        migrations.AddField(
            model_name='assureur',
            name='code_NCP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.comptebancaire'),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='Num_souscription_voyage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.souscriptiondevoyage'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
