# Generated by Django 3.1.7 on 2021-09-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0019_auto_20210914_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitassurance',
            old_name='code_produit',
            new_name='id_code_produit',
        ),
        migrations.RemoveField(
            model_name='baremedecredit',
            name='produitassurancee',
        ),
        migrations.AlterField(
            model_name='baremedecredit',
            name='code_produit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.produitassurance'),
        ),
        migrations.AlterField(
            model_name='baremedevoyage',
            name='code_produit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.produitassurance'),
        ),
        migrations.AlterField(
            model_name='souscriptiondecredit',
            name='Num_dossierCredit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.credit'),
        ),
        migrations.AlterField(
            model_name='souscriptiondecredit',
            name='code_produit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.produitassurance'),
        ),
        migrations.AlterField(
            model_name='souscriptiondevoyage',
            name='Num_fiche_client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.clientuib'),
        ),
    ]
