# Generated by Django 3.1.7 on 2021-09-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0020_auto_20210914_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitassurance',
            old_name='id_code_produit',
            new_name='id_code',
        ),
        migrations.AddField(
            model_name='produitassurance',
            name='code_produit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
