# Generated by Django 3.1.7 on 2021-09-15 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0024_auto_20210915_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitassurance',
            old_name='code_du_produit',
            new_name='code_produit',
        ),
    ]
