# Generated by Django 3.1.7 on 2021-09-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0025_auto_20210915_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='baremedecredit',
            name='code_assureur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.assureur'),
        ),
    ]
