# Generated by Django 3.1.7 on 2021-09-15 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0026_baremedecredit_code_assureur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assureur',
            name='code_NCP',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.comptebancaire'),
        ),
    ]
