# Generated by Django 3.1.7 on 2021-09-16 20:49

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0027_auto_20210915_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assureur',
            name='Telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
