# Generated by Django 3.1.7 on 2021-09-16 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0028_auto_20210916_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baremedecredit',
            name='code_produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.produitassurance', unique=True),
        ),
    ]
