# Generated by Django 3.1.7 on 2021-09-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0029_auto_20210916_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitassurance',
            name='Frais_MEP_asssureur',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='produitassurance',
            name='Frais_MEP_banque',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='produitassurance',
            name='etat_produit',
            field=models.CharField(choices=[('Valide', 'Valide'), ('En attente', 'En attente')], max_length=40),
        ),
        migrations.AlterField(
            model_name='produitassurance',
            name='part_assureur',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='produitassurance',
            name='part_banque',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='produitassurance',
            name='retenue_source',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
