# Generated by Django 3.1.7 on 2021-09-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0030_auto_20210917_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitassurance',
            name='TVA',
            field=models.IntegerField(blank=True),
        ),
    ]
