# Generated by Django 3.1.7 on 2021-09-17 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0031_auto_20210917_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='souscriptiondevoyage',
            name='Num_compte',
        ),
        migrations.AddField(
            model_name='souscriptiondevoyage',
            name='code_NCP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assurance.comptebancaire'),
        ),
    ]
