# Generated by Django 3.1.7 on 2021-09-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0032_auto_20210917_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='souscriptiondevoyage',
            old_name='Code_produit',
            new_name='code_produit',
        ),
    ]
