# Generated by Django 3.1.7 on 2021-09-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0035_auto_20210922_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitvoyage',
            name='type_produit',
        ),
    ]
